# Generated by Django 3.2.5 on 2021-10-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='title',
        ),
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
